#!/bin/sh

# Initialize submodules
git submodule init
git submodule update

# Create directories
mkdir ".vim/view"
mkdir ".vim/tags"
mkdir ".vim/local-config"
mkdir ".vim/yankring"
mkdir ".vim/notes"
mkdir ".vim/local-snippets"
