vim.keymap.del('n', 'yo')
vim.keymap.set('n', 'yol', function()
  vim.opt_local.list = not vim.opt_local.list:get()
end, { silent = true, buffer = true })
vim.keymap.set('n', 'yos', function()
  vim.opt_local.spell = not vim.opt_local.spell:get()
end, { silent = true, buffer = true })
vim.keymap.set('n', 'yow', function()
  vim.opt_local.wrap = not vim.opt_local.wrap:get()
end, { silent = true, buffer = true })
